### ISSUE TITLE
Add license info to package.json

### ISSUE THREAD

**Issue by kevinsawicki** [groupon/cson-safe#15]
This is MIT licensed right? Could you add `"license": "MIT"` to the `package.json` to make automated license checking easier?

**Comment by kevinsawicki** [comment]
Or sorry, looks like BSD?

**Comment by jkrems** [comment]
It's BSD 2-clause. Will update `package.json. Had to use a license checker myself because I couldn't remember.

**Comment by jkrems** [comment]
v1.0.3 (no other changes)
