### ISSUE TITLE
Hard tabs fail to parse

### ISSUE THREAD

**Issue by kevinsawicki** [groupon/cson-safe#20]
The following content does not parse if using `\t`:

```coffee
'a':
  'b':
    'c': """
d
  e
"""
```

But switching from `\t` to a two space indent works fine.

**Comment by johan** [comment]
Interesting. Works without the e:

```shell
node -e 'console.log(require("cson-safe").parse("a:\n\tb:\n\t\tc: \"\"\"\nd\n\t\"\"\""));'
node -e 'console.log(require("cson-safe").parse("c: \"\"\"\nd\n\t\"\"\""));'
```

Doesn't work with it:

```shell
node -e 'console.log(require("cson-safe").parse("a:\n\tb:\n\t\tc: \"\"\"\nd\n\te\"\"\""));'
node -e 'console.log(require("cson-safe").parse("c: \"\"\"\nd\n\te\"\"\""));'
```

**Comment by kevinsawicki** [comment]
Yeah, looks like the hard tab in the string is what does it.

**Comment by kevinsawicki** [comment]
Hmm, I guess this is what `JSON.parse` is "supposed" to do, https://code.google.com/p/chromium/issues/detail?id=52560

Still seems odd though since the `\n` was unescaped and still parsed just fine.

**Comment by kevinsawicki** [comment]
Changing https://github.com/groupon/cson-safe/blob/950ef169214ef7698e335ae957022dcd6d706655/src/parse.coffee#L80 to handle strings with either quote type does fix it.

**Comment by jkrems** [comment]
v1.0.5
